server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#scheduler:
#  update:
#    starAvg: aaa
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/Diary?serverTimezone=Asia/Seoul #테이블 변경하기
    username: root
    password: 1234

  mvc:
    static-path-pattern: /static/**
    path match:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  jwt:
    refresh-token:
      cookie: refresh_token
    secret: aGFlY2hhbi1zcHJpbmctYm9vdC1kaXZpZGVuZC1wcm9qZWN0LXR1dG9yaWFsLWp3dC1zZWNyZXQta2V5Cg==

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 720583155896-dknq57bcptcjt067fs9a5r752tg5cfpd.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          naver:
            client-id: k1dXQS9_TZtO1rJtbnue
            client-secret: c4qfWHWRun
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            #redirect-uri: https://d3k8rrzs9omv1v.cloudfront.net/login/oauth2/code/naver

          kakao:
            authorization-grant-type: authorization_code
            client-id: d7b9c236fb3e60adef42489607a5e4cf
            client-secret: M9xT69chffalax8P3u88VLp0Fi6ojR8w
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            #redirect-uri: https://d3k8rrzs9omv1v.cloudfront.net/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-authentication-method: POST
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  data:
    redis:
      host: localhost
      port: 6379

targetUrl:
  success: https://d3k8rrzs9omv1v.cloudfront.net/oauth2/redirect
  fail: https://d3k8rrzs9omv1v.cloudfront.net/login # 프론트 로그인 페이지
